language: rust
rust:
  - stable
  - beta
  - nightly
before_install:
  - sudo apt-get install -y libclamav7 clamav-freshclam
  # Stop freshclam running automatically
  - sudo dpkg-reconfigure clamav-freshclam
  # Run now so we know it's up to date
  - sudo freshclam -v
script:
  - cargo build --verbose
  - cargo test --verbose
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true